"""Initial migration

Revision ID: 2cf1d53f57b7
Revises: 
Create Date: 2024-10-14 11:46:22.554237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2cf1d53f57b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diver_profiles', sa.Column('birth_date', sa.Date(), server_default='1970-01-01', nullable=False))
    op.alter_column('diver_profiles', 'first_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100),
               nullable=True)
    op.alter_column('diver_profiles', 'last_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diver_profiles', 'last_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100),
               nullable=False)
    op.alter_column('diver_profiles', 'first_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100),
               nullable=False)
    op.drop_column('diver_profiles', 'birth_date')
    # ### end Alembic commands ###
