# app/repositories/__init__.py
from app.repositories.diver_profile_repository import DiverProfileRepository
from app.repositories.diver_license_repository import DiverLicenseRepository
from app.repositories.diver_gear_repository import DiverGearRepository
from app.repositories.master_license_repository import MasterLicenseRepository
from app.repositories.master_dive_preference_repository import MasterDivePreferenceRepository
from .master_dive_site_repository import MasterDiveSiteRepository
from app.repositories.master_gear_repository import MasterGearRepository
from app.repositories.master_brand_repository import MasterBrandRepository
from app.repositories.master_gear_brand_repository import MasterGearBrandRepository
from app.repositories.master_color_repository import MasterColorRepository
from .master_marine_life_repository import MasterMarineLifeRepository
from app.repositories.dive_preference_repository import DivePreferenceRepository
from .master_dive_type_repository import MasterDiveTypeRepository
from .dive_log_repository import DiveLogRepository
from .diver_additional_data_repository import DiverAdditionalDataRepository